audio:
  fft_size: 512
  frame_shift_ms: 10
  frame_size_ms: 20
  sample_rate: 16000
  window_type: hanning
gain_calculation:
  alpha: 2.5
  alpha_smooth: 0.75
  beta: 0.01
  method: spectral_subtraction
name: Spectral Subtraction
noise_estimation:
  method: simple_average
  num_init_frames: 20
version: 1
